tabWidth: 2
useTabs: false

semi: false

singleQuote: true
jsxSingleQuote: true

quoteProps: 'consistent'
trailingComma: 'all'

bracketSpacing: true
bracketSameLine: false

arrowParens: avoid

endOfLine: 'lf'
